apiVersion: apps/v1
kind: Deployment
metadata:
  name: cfrhj
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cfrhj
  template:
    metadata:
      labels:
        app: cfrhj
    spec:
      containers:
      - image: okteto.dev/cfrhj:latest
        name: cfrhj
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/comila-html.zip"
        - name: Vless_UUID
          value: "4e53b427-54c3-4b6d-9c7e-80b3cfe54a8a"
        - name: Vless_Path
          value: "/4e53b427-54c3-4b6d-9c7e-80b3cfe54a8a-vless"
        - name: Vmess_UUID
          value: "4e53b427-54c3-4b6d-9c7e-80b3cfe54a8a"
        - name: Vmess_Path
          value: "/4e53b427-54c3-4b6d-9c7e-80b3cfe54a8a-vmess"
        - name: Share_Path
          value: "/vqqpk"
